# Generated by Django 2.2.5 on 2019-09-11 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
